version: '3'
services:
  frontend:
    build:
      dockerfile: Dockerfile
    ports:
      - 4000:3000
    volumes:
      - ./:/frontend
  db:
    image: mysql
    volumes:
      - mysql:/var/lib/mysql
    env_file: "./env/.env"
    environment: 
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - '3307:3306'

volumes:
  mysql:
    driver: local
