services:
  frontend:
    build:
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./:/frontend
    command: /bin/sh -c "npm install && node app.js"
  db:
    image: mysql
    volumes:
      - mysql:/var/lib/mysql
    env_file: "./env/.env"
    ports:
      - '3307:3306'

volumes:
  mysql:
    driver: local
